export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_TYPES = "GET_TYPES";
export const GET_DETAIL = "GET_DETAIL";
//export const GET_DETAIL_FROM_STATE = "GET_DETAIL_FROM_STATE";
export const GET_NAME_POKEMON = "GET_NAME_POKEMON";
export const POST_POKEMON = "POST_POKEMON";
export const LOADING = "LOADING";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_CREATED = "FILTER_CREATED";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_ATTACK = "ORDER_BY_ATTACK";
export const RESET_POKEMONS = "RESET_POKEMONS";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const CLEAR_HOME = "CLEAR_HOME";

